services:

  mongodb:
    image: mongo:6.0.1
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - ./.mongoEnv
    ports:
      - "27018:27017"
    volumes:
      - ./tmp-data:/data/db
    command: mongod --bind_ip_all

  app_name:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env
    links:
      - mongodb
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.routers.api.rule=Host(`local-api.appName.com`)"
    command: bash -c "yarn install && bash ./docker/run.sh"

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./tmp-data/minio:/data
    environment:
      - MINIO_ROOT_USER=access-key
      - MINIO_ROOT_PASSWORD=secret-key
      - MINIO_REGION=us-west-2
    command: server /data --console-address ":9001"

  proxy:
    image: "traefik:v2.7"
    command:
      # - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"